SPK_NAME = matter-server
SPK_VERS = 6.6.0
SPK_REV = 1
SPK_ICON = src/matter-server.png

PYTHON_PACKAGE = python311
SPK_DEPENDS = "python311>=3.11.5-8"
UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS)

DISPLAY_NAME = Matter Server
STARTABLE = yes
CHANGELOG = ""

HOMEPAGE = https://github.com/home-assistant-libs/python-matter-server

include ../../mk/spksrc.common.mk

include ../../mk/spksrc.python.mk
